gps = [{'gp': 'Australian', 'year': 2026, 'short': 'AUS', 'nextgp': False},
       {'gp': 'Chinese', 'year': 2026, 'short': 'CHN', 'nextgp': False},
       {'gp': 'Japanese', 'year': 2026, 'short': 'JPN', 'nextgp': False},
       {'gp': 'Bahrain', 'year': 2026, 'short': 'BHR', 'nextgp': False},
       {'gp': 'Saudi Arabian', 'short': 'SAU', 'year': 2026, 'nextgp': False},
       {'gp': 'Miami', 'year': 2026, 'short': 'MIA', 'nextgp': False},
       {'gp': 'Canadian', 'year': 2026, 'short': 'CAN', 'nextgp': False},
       {'gp': 'Monaco', 'year': 2026, 'short': 'MON', 'nextgp': False},
       {'gp': 'Barcelona-Catalunya', 'year': 2026, 'short': 'BAR', 'nextgp': False},
       {'gp': 'Austrian', 'year': 2026, 'short': 'AUT', 'nextgp': False},
       {'gp': 'British', 'year': 2026, 'short': 'GBR', 'nextgp': False},
       {'gp': 'Belgian', 'year': 2026, 'short': 'BEL', 'nextgp': False},
       {'gp': 'Hungarian', 'year': 2026, 'short': 'HUN', 'nextgp': False},
       {'gp': 'Dutch', 'year': 2026, 'short': 'NED', 'nextgp': False},
       {'gp': 'Italian', 'year': 2026, 'short': 'ITA', 'nextgp': False},
       {'gp': 'Spanish', 'year': 2025, 'short': 'ESP', 'nextgp': False},
       {'gp': 'Azerbaijan', 'year': 2026, 'short': 'AZE', 'nextgp': False},
       {'gp': 'Singapore', 'year': 2026, 'short': 'SIN', 'nextgp': False},
       {'gp': 'United States', 'year': 2026, 'short': 'USA', 'nextgp': False},
       {'gp': 'Mexico City', 'year': 2026, 'short': 'MXC', 'nextgp': True},
       {'gp': 'São Paulo', 'year': 2026, 'short': 'SAP', 'nextgp': False},
       {'gp': 'Las Vegas', 'year': 2026, 'short': 'LVG', 'nextgp': False},
       {'gp': 'Qatar', 'year': 2026, 'short': 'QAT', 'nextgp': False},
       {'gp': 'Abu Dhabi', 'year': 2026, 'short': 'ABU', 'nextgp': False}
       ]
