drivers = [{'driver': 'Max Verstappen', 'points': 362, 'nextGP': 'Y'},
{'driver': 'Lando Norris', 'points': 315, 'nextGP': 'Y'},
{'driver': 'Charles Leclerc', 'points': 291, 'nextGP': 'Y'},
{'driver': 'Oscar Piastri', 'points': 251, 'nextGP': 'Y'},
{'driver': 'Carlos Sainz', 'points': 240, 'nextGP': 'Y'},
{'driver': 'Lewis Hamilton', 'points': 189, 'nextGP': 'Y'},
{'driver': 'George Russell', 'points': 177, 'nextGP': 'Y'},
{'driver': 'Sergio Pérez', 'points': 150, 'nextGP': 'Y'},
{'driver': 'Fernando Alonso', 'points': 62, 'nextGP': 'Y'},
{'driver': 'Nico Hülkenberg', 'points': 31, 'nextGP': 'Y'},
{'driver': 'Lance Stroll', 'points': 24, 'nextGP': 'Y'},
{'driver': 'Yuki Tsunoda', 'points': 22, 'nextGP': 'Y'},
{'driver': 'Kevin Magnussen', 'points': 14, 'nextGP': 'Y'},
{'driver': 'Alexander Albon', 'points': 12, 'nextGP': 'Y'},
{'driver': 'Daniel Ricciardo', 'points': 12, 'nextGP': 'N'},
{'driver': 'Pierre Gasly', 'points': 9, 'nextGP': 'Y'},
{'driver': 'Oliver Bearman', 'points': 7, 'nextGP': 'N'},
{'driver': 'Franco Colapinto', 'points': 5, 'nextGP': 'Y'},
{'driver': 'Esteban Ocon', 'points': 5, 'nextGP': 'Y'},
{'driver': 'Liam Lawson', 'points': 2, 'nextGP': 'Y'},
{'driver': 'Zhou Guanyu', 'points': 0, 'nextGP': 'Y'},
{'driver': 'Logan Sargeant', 'points': 0, 'nextGP': 'N'},
{'driver': 'Valtteri Bottas', 'points': 0, 'nextGP': 'Y'}]

players = []