drivers = [{'driver': 'Max Verstappen', 'team': 'Red Bull', 'engine': 'Red Bull', 'position': 1, 'nextGP': 1, 'engine_short': '🟣'},
           {'driver': 'Lando Norris', 'team': 'McLaren', 'engine': 'Mercedes', 'position': 2, 'nextGP': 1, 'engine_short': '⚫'},
           {'driver': 'Charles Leclerc', 'team': 'Ferrari', 'engine': 'Ferrari', 'position': 3, 'nextGP': 1, 'engine_short': '🔴'},
           {'driver': 'Oscar Piastri', 'team': 'McLaren', 'engine': 'Mercedes', 'position': 4, 'nextGP': 1, 'engine_short': '⚫'},
           {'driver': 'Carlos Sainz', 'team': 'Williams', 'engine': 'Mercedes', 'position': 5, 'nextGP': 1, 'engine_short': '⚫'},
           {'driver': 'Lewis Hamilton', 'team': 'Ferrari', 'engine': 'Ferrari', 'position': 7, 'nextGP': 1, 'engine_short': '🔴'},
           {'driver': 'George Russell', 'team': 'Mercedes', 'engine': 'Mercedes', 'position': 6, 'nextGP': 1, 'engine_short': '⚫'},
           {'driver': 'Liam Lawson', 'team': 'Red Bull', 'engine': 'Red Bull', 'position': 8, 'nextGP': 1, 'engine_short': '🟣'},
           {'driver': 'Fernando Alonso', 'team': 'Aston Martin', 'engine': 'Mercedes', 'position': 9, 'nextGP': 1, 'engine_short': '⚫'},
           {'driver': 'Nico Hülkenberg', 'team': 'Sauber', 'engine': 'Ferrari', 'position': 11, 'nextGP': 1, 'engine_short': '🔴'},
           {'driver': 'Lance Stroll', 'team': 'Aston Martin', 'engine': 'Mercedes', 'position': 13, 'nextGP': 1, 'engine_short': '⚫'},
           {'driver': 'Yuki Tsunoda', 'team': 'Racing Bulls', 'engine': 'Red Bull', 'position': 12, 'nextGP': 1, 'engine_short': '🟣'},
           {'driver': 'Gabriel Bortoleto', 'team': 'Sauber', 'engine': 'Ferrari', 'position': 20, 'nextGP': 1, 'engine_short': '🔴'},
           {'driver': 'Alexander Albon', 'team': 'Williams', 'engine': 'Mercedes', 'position': 15, 'nextGP': 1, 'engine_short': '⚫'},
           {'driver': 'Jack Doohan', 'team': 'Alpine', 'engine': 'Renault', 'position': 18, 'nextGP': 1, 'engine_short': '🟡'},
           {'driver': 'Pierre Gasly', 'team': 'Alpine', 'engine': 'Renault', 'position': 10, 'nextGP': 1, 'engine_short': '🟡'},
           {'driver': 'Oliver Bearman', 'team': 'Haas', 'engine': 'Ferrari', 'position': 16, 'nextGP': 1, 'engine_short': '🔴'},
           {'driver': 'Andrea Kimi Antonelli', 'team': 'Mercedes', 'engine': 'Mercedes', 'position': 19, 'nextGP': 1, 'engine_short': '⚫'},
           {'driver': 'Esteban Ocon', 'team': 'Haas', 'engine': 'Ferrari', 'position': 14, 'nextGP': 1, 'engine_short': '🔴'},
           {'driver': 'Isack Hadjar', 'team': 'Racing Bulls', 'engine': 'Red Bull', 'position': 17, 'nextGP': 1, 'engine_short': '🟣'}]
